### ISSUE TITLE
Using Oauth App Token

### ISSUE THREAD

**Issue by alldoami** [imjohnbo/ok-to-test#10]
I want to use the OAuth App method to authenticate, but how do you create the token in the first place? I see that you're intending to use secrets in the `Slash Command Dispatch`, but how does the token get created and put into Github secrets?

My interpretation was for this code:
```
- name: Slash Command Dispatch
      uses: peter-evans/slash-command-dispatch@v1
      env:
        TOKEN: ${{ steps.generate_token.outputs.token }}
      with:
        token: ${{ env.TOKEN }} # GitHub App installation access token
        # token: ${{ secrets.PERSONAL_ACCESS_TOKEN }} # PAT or OAuth token will also work
        reaction-token: ${{ secrets.GITHUB_TOKEN }}
        issue-type: pull-request
        commands: ok-to-test
        named-args: true
        permission: write
```
to become 
```
- name: Slash Command Dispatch
      uses: peter-evans/slash-command-dispatch@v1
      with:
        token: ${{ secrets.OAUTH-TOKEN}} # PAT or OAuth token will also work
        reaction-token: ${{ secrets.GITHUB_TOKEN }}
        issue-type: pull-request
        commands: ok-to-test
        named-args: true
        permission: write
```
but that implies that there is a `OAUTH-TOKEN` in Github secrets. I know that the PAT is easy to create and put into secrets, but when creating an [OAuth App in the UI](https://docs.github.com/en/free-pro-team@latest/developers/apps/creating-an-oauth-app), there's no where suggesting how to create a token. I'm reading steps #2 and #3 from these [docs](https://docs.github.com/en/free-pro-team@latest/developers/apps/authorizing-oauth-apps), but there's nothing about putting that token into Github secrets... Any guidance would help! I see that the flow using the Github app installation is well-documented, but using the Oauth token doesn't have an example, one would be appreciated!
